"""
data_loader.py — Unified data loading for all Q1/Q2 scripts
Reads clean_data.csv (generated by step0_preprocess.py).
All Q2 scripts should import from here to ensure consistent data.
"""

import os, numpy as np, pandas as pd

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CLEAN_CSV = os.path.join(BASE_DIR, "output", "clean_data.csv")
EPS = 1e-3

STD_COLS = [
    "DATE", "TIME", "RIVER_LEVEL", "RW_NTU", "RW_CLR", "RW_PH",
    "FILT_NTU", "CW_WELL_LEVEL", "PH", "NTU", "CLR", "CL2",
    "ALUM", "TW_FLOW", "RW_FLOW",
]


def load_clean_data(path=None):
    """Load clean_data.csv with unified NaN handling and column standardization.
    
    Returns:
        pd.DataFrame with consistent columns and NaN handling.
        All Q2 scripts should use this function.
    """
    fp = path or CLEAN_CSV
    if not os.path.exists(fp):
        raise FileNotFoundError(f"clean_data.csv not found at {fp}. Run step0_preprocess.py first.")
    
    df = pd.read_csv(fp)
    
    # Drop rows with missing target
    df = df.dropna(subset=["FILT_NTU"]).reset_index(drop=True)
    
    # Fill missing numeric columns with median
    num_cols = df.select_dtypes(include=[np.number]).columns
    for c in num_cols:
        if df[c].isna().sum() > 0:
            df[c] = df[c].fillna(df[c].median())
    
    return df


def get_time_features(df):
    """Generate hour/month sin/cos features from TIME and MONTH columns."""
    time_vals = pd.to_numeric(df["TIME"], errors="coerce").fillna(700).astype(int)
    hour = (time_vals // 100) % 24
    
    features = {
        "hour": hour,
        "hour_sin": np.sin(2 * np.pi * hour / 24),
        "hour_cos": np.cos(2 * np.pi * hour / 24),
    }
    
    if "MONTH" in df.columns:
        month = df["MONTH"].values.astype(int)
        features["month"] = month
        features["month_sin"] = np.sin(2 * np.pi * month / 12)
        features["month_cos"] = np.cos(2 * np.pi * month / 12)
    
    return features


def get_arrays(df):
    """Extract numpy arrays for common variables."""
    out = {}
    for col in ["RIVER_LEVEL", "RW_NTU", "RW_CLR", "RW_PH", "RW_FLOW",
                 "FILT_NTU", "CW_WELL_LEVEL", "TW_FLOW", "ALUM", "NTU", "CLR"]:
        if col in df.columns:
            out[col] = df[col].values.astype(np.float64)
    return out


if __name__ == "__main__":
    df = load_clean_data()
    print(f"Loaded {len(df)} rows, {len(df.columns)} columns")
    print(f"Columns: {list(df.columns)}")
